name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort bandit

      - name: Run black
        run: black -l 120 --check --diff --safe .

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: python -m isort --check-only --diff .

      - name: Run bandit
        run: bandit -r .